<<<<<<< HEAD
AUDIO = 'audio'
BLINK = 'blink'
ENGINE = 'engine'
EYETRACKER = 'eyetracker'
FACE = 'face'
FACE_WINDOW = 'face_window'
GO = 'go'
LAYOUT = 'layout'
SYSTEM = 'system'
SYSTEM = 'system'
TEST = 'test'
TKPIECE = 'tkpiece'
WFACE = 'wface'
ZCONSOLE = 'zconsole'
ZPRINTER = 'zprinter'
=======
AUDIO = 'audio'
BLINK = 'blink'
ENGINE = 'engine'
EYETRACKER = 'eyetracker'
FACE = 'face'
FACE_WINDOW = 'face_window'
GO = 'go'
LAYOUT = 'layout'
MOUSE_TO_EYE = 'mouse_to_eye'
SYSTEM = 'system'
SYSTEM = 'system'
TEST = 'test'
TKPIECE = 'tkpiece'
WFACE = 'wface'
ZCONSOLE = 'zconsole'
ZPRINTER = 'zprinter'
>>>>>>> 122e1a3c16edb826d81bca6847bfe3ca393e0773
PIECE = 'piece'